services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: degovapps
      POSTGRES_PASSWORD: let-me-in
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
      # command: ["postgres", "-c", "log_statement=all"]
    shm_size: 1gb
