name: Check

on:
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - web
    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install deps
        run: |
          cd ${{ matrix.package }}
          pnpm install

      - name: Check Build
        run: |
          cd ${{ matrix.package }}
          pnpm build
