name: Check

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  check-web:
    name: Check Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install deps
        working-directory: web
        run: |
          pnpm install

      - name: Check Build
        working-directory: web
        run: |
          pnpm build

  check-backend:
    name: Check Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5

      - name: Check Build
        working-directory: backend
        run: |
          make generate
          make deps
          make build
