name: Release

on:
  # pull_request:
  #   branches: [main]
  workflow_dispatch:
  push:
    tags:
      - "v*"

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  release-backend:
    name: Release backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}

      - uses: benjlevesque/short-sha@v3.0
      - uses: olegtarasov/get-tag@v2.1.4
      - name: Get branch names.
        id: branch-names
        uses: tj-actions/branch-names@v9

      - name: Publish docker image hash
        uses: docker/build-push-action@v6
        if: startsWith(github.ref, 'refs/heads/')
        with:
          push: true
          context: backend
          file: backend/Dockerfile
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/backend:sha-${{ env.SHA }}
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/backend:staging
          build-args: |
            APP_VERSION=${{ steps.branch-names.outputs.current_branch }}-${{ env.SHA }}

      - name: Publish docker image tag
        uses: docker/build-push-action@v6
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          push: true
          context: backend
          file: backend/Dockerfile
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/backend:sha-${{ env.SHA }}
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/backend:${{ env.GIT_TAG_NAME }}
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/backend:latest
          build-args: |
            APP_VERSION=${{ env.GIT_TAG_NAME }}-${{ env.SHA }}
