name: Release

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
  push:
    tags:
      - "v*"

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  release-backend:
    name: Release backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}

      - uses: benjlevesque/short-sha@v3.0
      - uses: olegtarasov/get-tag@v2.1.4

      - name: Publish docker image hash
        uses: docker/build-push-action@v6
        with:
          push: true
          context: backend
          file: backend/Dockerfile
          tags: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/backend:sha-${{ env.SHA }}

      - name: Publish docker image tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          IMAGE_TAG_HASH=${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/backend
          docker tag ${IMAGE_TAG_HASH}:sha-${{ env.SHA }} ${IMAGE_TAG_HASH}:${{ env.GIT_TAG_NAME }}
          docker push ${IMAGE_TAG_HASH}:${{ env.GIT_TAG_NAME }}
